
import { Song, Language } from './types';

export const SONGS_PLAYLIST: Song[] = [
  {
    titleMk: "Зајди, зајди, јасно сонце",
    titleEn: "Zajdi, Zajdi, Bright Sun",
    titleRu: "Зайди, зайди, ясное солнце",
    artistMk: "Александар Сариевски",
    artistEn: "Aleksandar Sarievski",
    artistRu: "Александр Сариевский",
    descriptionMk: "Оваа безвременска елегија, стоплена од треперливиот глас на великанот Александар Сариевски, е најдлабокиот крик на македонската душа пред минливоста на животот. Нејзината мелодија нежно, како зајдисонце, ја оплакува изгубената младост, оставајќи топла лузна во секое срце што ќе ја слушне. Таа не е само песна, туку искрена и утешна прегратка која вечно ги чува нашите најемотивни спомени.",
    descriptionEn: "This timeless elegy, warmed by the trembling voice of the great Aleksandar Sarievski, is the deepest cry of the Macedonian soul in the face of life's transience. Its melody gently, like a sunset, mourns lost youth, leaving a warm scar in every heart that hears it. It is not just a song, but a sincere and comforting embrace that eternally guards our most emotional memories.",
    descriptionRu: "Эта вневременная элегия, согретая трепетным голосом великого Александара Сариевского, является самым глубоким криком македонской души перед быстротечностью жизни. Ее мелодия нежно, как закат, оплакивает утраченную молодость, оставляя теплый след в каждом сердце, которое ее слышит. Это не просто песня, а искреннее и утешительное объятие, вечно хранящее наши самые эмоциональные воспоминания."
  },
  {
    titleMk: "Јовано, Јованке",
    titleEn: "Jovano, Jovanke",
    titleRu: "Йовано, Йованке",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Безвременска македонска песна во која љубовта и болката стојат една до друга со тивка убавина. Во неа живее копнежот што народот со генерации го пренесува како дел од својата музичка и духовна традиција. Таа е еден од најнежните симболи на македонската народна песна.",
    descriptionEn: "A timeless Macedonian song in which love and sorrow stand side by side with quiet beauty. It carries a longing that generations have passed on as part of their musical and spiritual tradition. It is one of the gentlest symbols of Macedonian folk song.",
    descriptionRu: "Вневременная македонская песня, в которой любовь и боль стоят рядом с тихой красотой. В ней живёт тоска, которую поколения передавали как часть своей музыкальной и духовной традиции. Она остаётся одним из самых нежных символов македонской народной песни."
  },
  {
    titleMk: "Македонско девојче",
    titleEn: "Macedonian Girl",
    titleRu: "Македонская девушка",
    artistMk: "Јонче Христовски",
    artistEn: "Jonce Hristovski",
    artistRu: "Йонче Христовский",
    descriptionMk: "Светла и горда песна што ја слави убавината, ведрината и достоинството на македонската девојка. Низ неа се чувствува топлината на народниот дух и радоста што традиционалната песна ја носи од поколение на поколение. Таа одамна прерасна во препознатлив знак на македонската музичка култура.",
    descriptionEn: "A bright and proud song celebrating the beauty, warmth, and dignity of the Macedonian girl. It reflects the warmth of the people’s spirit and the joy that traditional song carries from generation to generation. It has long become a recognizable symbol of Macedonian musical culture.",
    descriptionRu: "Светлая и гордая песня, прославляющая красоту, душевность и достоинство македонской девушки. В ней ощущается тепло народного духа и радость, которую традиционная песня несёт из поколения в поколение. Она давно стала узнаваемым символом македонской музыкальной культуры."
  },
  {
    titleMk: "Ако одам во Битола",
    titleEn: "If I Go to Bitola",
    titleRu: "Если я поеду в Битолу",
    artistMk: "Петар Георгиев - Калица",
    artistEn: "Petar Georgiev - Kalica",
    artistRu: "Петар Георгиев — Калица",
    descriptionMk: "Тивка музичка разгледница на Битола, исполнета со безмерна топлина и носталгија. Во неа совршено се чувствува духот на Широк Сокак и градската гордост што се пренесува низ генерации. Оваа песна останува како едно нежно, вечно љубовно писмо до градот на конзулите кој никогаш не се заборава.",
    descriptionEn: "A quiet musical postcard of Bitola, filled with immense warmth and nostalgia. The spirit of Shirok Sokak and the civic pride passed down through generations are perfectly felt within it. This song remains as a tender, eternal love letter to the city of consuls that is never forgotten.",
    descriptionRu: "Тихая музыкальная открытка Битолы, наполненная безмерным теплом и ностальгией. В ней прекрасно чувствуется дух Широк Сокака и городская гордость, передающаяся из поколения в поколение. Эта песня остается нежным, вечным любовным письмом городу консулов, который никогда не забывается."
  },
  {
    titleMk: "Земјо македонска",
    titleEn: "Macedonian Land",
    titleRu: "Земля македонская",
    artistMk: "Васка Илиева",
    artistEn: "Vaska Ilieva",
    artistRu: "Васка Илиева",
    descriptionMk: "Песна што со топол и достоинствен тон ја опева Македонија, нејзините предели, луѓе и непокорен дух. Во неа живее љубовта кон татковината како природно чувство вградено во народната песна. Таа останува еден од најсилните музички изрази на македонската припадност и традиција.",
    descriptionEn: "A song that praises Macedonia, its landscapes, people, and resilient spirit with warmth and dignity. It carries love for the homeland as a natural feeling woven into folk song. It remains one of the strongest musical expressions of Macedonian belonging and tradition.",
    descriptionRu: "Песня, которая с теплом и достоинством воспевает Македонию, её пейзажи, людей и непокорный дух. В ней живёт любовь к родине как естественное чувство, вплетённое в народную песню. Она остаётся одним из самых сильных музыкальных выражений македонской принадлежности и традиции."
  },
  {
    titleMk: "Билјана платно белеше",
    titleEn: "Biljana Bleached Linen",
    titleRu: "Биляна отбеливала полотно",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Една од најпрепознатливите македонски народни песни, во која секојдневната слика крај водата се претвора во чиста поезија. Во неа се среќаваат младоста, убавината и тивкиот љубовен поглед што народот го памети со векови. Песната блеска како бисер на традиционалната македонска песна.",
    descriptionEn: "One of the most recognizable Macedonian folk songs, where an everyday scene by the water turns into pure poetry. It brings together youth, beauty, and a quiet loving glance remembered by the people for centuries. The song shines as a jewel of traditional Macedonian music.",
    descriptionRu: "Одна из самых узнаваемых македонских народных песен, в которой повседневная сцена у воды превращается в чистую поэзию. В ней встречаются молодость, красота и тихий влюблённый взгляд, который народ помнит веками. Песня сияет как драгоценность традиционной македонской музыки."
  },
  {
    titleMk: "Дејгиди луди млади години",
    titleEn: "Oh, Those Crazy Young Years",
    titleRu: "Ох, эти сумасшедшие молодые годы",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Топла носталгија за убавината на младоста која неповратно и пребрзо минува. Во нејзиниот жив ритам истовремено треперат горда насмевка и една скриена солза. Песната е мудар потсетник дека најубавите години во животот секогаш траат најкратко.",
    descriptionEn: "A warm nostalgia for the beauty of youth that irreversibly and too quickly passes. In its lively rhythm, a proud smile and a hidden tear quiver simultaneously. The song is a wise reminder that the best years in life always last the shortest.",
    descriptionRu: "Теплая ностальгия по красоте молодости, которая необратимо и слишком быстро проходит. В ее живом ритме одновременно трепещут гордая улыбка и скрытая слеза. Песня — мудрое напоминание о том, что лучшие годы в жизни всегда длятся меньше всего."
  },
  {
    titleMk: "Кажи, кажи либе Стано",
    titleEn: "Tell Me, Tell Me, Beloved Stana",
    titleRu: "Скажи, скажи, любимая Стана",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Нежен љубовен дијалог во кој се слуша чистотата на старите македонски обичаи и искреноста на народното додворување. Во неа нема претераност, туку топлина, мерак и блискост. Песната е убав пример за меката и човечка страна на македонската традиционална музика.",
    descriptionEn: "A gentle love dialogue that reflects the purity of old Macedonian customs and the sincerity of traditional courtship. It holds warmth, affection, and closeness without excess. The song is a fine example of the soft and human side of Macedonian traditional music.",
    descriptionRu: "Нежный любовный диалог, в котором слышится чистота старых македонских обычаев и искренность народного ухаживания. В ней нет чрезмерности, а есть тепло, душевность и близость. Песня остаётся прекрасным примером мягкой и человечной стороны македонской традиционной музыки."
  },
  {
    titleMk: "Бисер балкански",
    titleEn: "Balkan Pearl",
    titleRu: "Балканская жемчужина",
    artistMk: "Гоце Николовски",
    artistEn: "Goce Nikolovski",
    artistRu: "Гоце Николовски",
    descriptionMk: "Оваа величествена музичка ода, отпеана низ моќниот глас на Гоце Николовски, во срцата на народот со право живее како втора македонска химна. Нејзините топли стихови будат неизмерна гордост и љубов кон секоја педа од татковината, славејќи ги нејзините природни убавини и славна историја. Таа претставува силна емотивна нишка што трајно ги обединува Македонците, каде и да се наоѓаат низ светот.",
    descriptionEn: "This magnificent musical ode, sung through the powerful voice of Goce Nikolovski, rightfully lives in the hearts of the people as a second Macedonian anthem. Its warm verses awaken immense pride and love for every inch of the homeland, celebrating its natural beauties and glorious history. It represents a strong emotional thread that permanently unites Macedonians, wherever they are in the world.",
    descriptionRu: "Эта великолепная музыкальная ода, спетая мощным голосом Гоце Николовского, по праву живет в сердцах народа как второй македонский гимн. Ее теплые стихи пробуждают безмерную гордость и любовь к каждой пяди родины, прославляя ее природные красоты и славную историю. Она представляет собой прочную эмоциональную нить, навсегда объединяющую македонцев, где бы они ни находились в мире."
  },
  {
    titleMk: "Лихнида кајче веслаше",
    titleEn: "Lihnida Rowed a Boat",
    titleRu: "Лихнида гребла в лодке",
    artistMk: "Ефто Пупиновски",
    artistEn: "Efto Pupinovski",
    artistRu: "Ефто Пупиновски",
    descriptionMk: "Прекрасна романтична слика инспирирана од волшебната тишина на Охридското Езеро. Мелодијата носи лесно, смирувачко движење, како мал бран што полека се распрснува кон брегот. Во неа за засекогаш живее спокојот на бистрата вода и еден тивок, нежен копнеж.",
    descriptionEn: "A beautiful romantic image inspired by the magical silence of Lake Ohrid. The melody carries a light, soothing movement, like a small wave slowly breaking against the shore. The serenity of the clear water and a quiet, tender longing live within it forever.",
    descriptionRu: "Прекрасный романтический образ, вдохновленный волшебной тишиной Охридского озера. Мелодия несет легкое, успокаивающее движение, как маленькая волна, медленно разбивающаяся о берег. В ней навсегда живет безмятежность прозрачной воды и тихая, нежная тоска."
  },
  {
    titleMk: "Битола, мој роден крај",
    titleEn: "Bitola, My Hometown",
    titleRu: "Битола, мой родной край",
    artistMk: "Ајри Демировски",
    artistEn: "Ajri Demirovski",
    artistRu: "Айри Демировски",
    descriptionMk: "Длабоко емотивна химна за враќањето кон домот и спомените што неизбришливо го греат срцето. Низ нејзината меланхолична мелодија повторно оживуваат калдрмите и гласовите на детството. Таа тивко, но силно ја чува светата врска меѓу човекот и местото од кое потекнува.",
    descriptionEn: "A deeply emotional anthem about returning home and the memories that indelibly warm the heart. Through its melancholic melody, the cobblestones and voices of childhood come alive once more. It quietly but strongly preserves the sacred bond between a person and their place of origin.",
    descriptionRu: "Глубоко эмоциональный гимн о возвращении домой и воспоминаниях, которые неизгладимо согревают сердце. Сквозь ее меланхоличную мелодию вновь оживают брусчатка и голоса детства. Она тихо, но сильно хранит священную связь между человеком и местом его происхождения."
  },
  {
    titleMk: "Жал за Деспина",
    titleEn: "Sorrow for Despina",
    titleRu: "Скорбь по Деспине",
    artistMk: "Наум Петрески",
    artistEn: "Naum Petreski",
    artistRu: "Наум Петрески",
    descriptionMk: "Искрена и тивка тага по една изгубена љубов, мајсторски преточена во нежна мелодија. Секој отпеан стих носи огромна тежина на спомен што пркоси на времето и не избледува. Песната останува како вечен одек на еден копнеж што никогаш не наоѓа мир.",
    descriptionEn: "A sincere and quiet sorrow for a lost love, masterfully translated into a gentle melody. Every sung verse carries the immense weight of a memory that defies time and does not fade. The song remains as an eternal echo of a longing that never finds peace.",
    descriptionRu: "Искренняя и тихая печаль по утраченной любви, мастерски переведенная в нежную мелодию. Каждый спетый стих несет огромную тяжесть воспоминания, которое бросает вызов времени и не тускнеет. Песня остается вечным эхом тоски, которая никогда не находит покоя."
  },
  {
    titleMk: "Ако згрешам нека изгорам",
    titleEn: "If I Sin, Let Me Burn",
    titleRu: "Если я согрешу, пусть сгорю",
    artistMk: "Пепи Бафтировски",
    artistEn: "Pepi Baftirovski",
    artistRu: "Пепи Бафтировски",
    descriptionMk: "Моќна и бескомпромисна љубовна заклетва, изговорена со силен жар и без ниту малку двоумење. Во неа чувствата се апсолутно чисти и крајни, не оставајќи простор за никаков компромис. Песната носи емотивна топлина што тлее во душата долго по последниот тон.",
    descriptionEn: "A powerful and uncompromising vow of love, spoken with intense fervor and without the slightest hesitation. In it, the feelings are absolutely pure and absolute, leaving no room for any compromise. The song carries an emotional warmth that smolders in the soul long after the last note.",
    descriptionRu: "Мощная и бескомпромиссная клятва любви, произнесенная с сильным пылом и без малейших колебаний. В ней чувства абсолютно чисты и абсолютны, не оставляя места ни для каких компромиссов. Песня несет эмоциональное тепло, которое тлеет в душе еще долго после последней ноты."
  },
  {
    titleMk: "Заветна",
    titleEn: "The Pledge",
    titleRu: "Заветная",
    artistMk: "Пепи Бафтировски",
    artistEn: "Pepi Baftirovski",
    artistRu: "Пепи Бафтировски",
    descriptionMk: "Мирна, но исклучително цврста света порака за припадноста, корените и љубовта кон татковината. Во нејзиниот горд ритам пулсира истрајноста на еден народ што се пренесува низ вековите. Песната остава тивка, но длабока и неизбришлива трага во секое срце.",
    descriptionEn: "A calm, yet exceptionally firm sacred message about belonging, roots, and love for the homeland. In its proud rhythm pulsates the perseverance of a nation passed down through centuries. The song leaves a quiet, but deep and indelible mark in every heart.",
    descriptionRu: "Спокойное, но исключительно твердое священное послание о принадлежности, корнях и любви к родине. В ее гордом ритме пульсирует стойкость народа, передаваемая веками. Песня оставляет тихий, но глубокий и неизгладимый след в каждом сердце."
  },
  {
    titleMk: "Сине мој",
    titleEn: "My Son",
    titleRu: "Мой сын",
    artistMk: "Гоце Арнаудов",
    artistEn: "Goce Arnaudov",
    artistRu: "Гоце Арнаудов",
    descriptionMk: "Потресна и нежна родителска исповед, исполнета со неизмерна грижа и безусловна љубов. Во неа се слуша тивката, но моќна молитва за добар пат и достоинствен живот на своето чедо. Оваа песна претставува топол глас кој вечно води низ животните искушенија.",
    descriptionEn: "A moving and gentle parental confession, filled with immense care and unconditional love. Within it, one hears the quiet but powerful prayer for a good path and a dignified life for their child. This song represents a warm voice that eternally guides through life's trials.",
    descriptionRu: "Трогательная и нежная родительская исповедь, наполненная безмерной заботой и безусловной любовью. В ней слышится тихая, но сильная молитва о добром пути и достойной жизни для своего ребенка. Эта песня представляет собой теплый голос, вечно ведущий через жизненные испытания."
  },
  {
    titleMk: "Оган да го гори",
    titleEn: "Let Fire Burn Him",
    titleRu: "Пусть огонь сожжёт его",
    artistMk: "Петранка Костадинова",
    artistEn: "Petranka Kostadinova",
    artistRu: "Петранка Костадинова",
    descriptionMk: "Бурен израз на повредена доверба и длабока, нескриена емоција. Извонредниот вокал ја носи целата тежина на клетвата, но и прочистувачкото олеснување што доаѓа по неа. Ова дело маестрално ја претвора човечката болка во силен и ослободувачки звук.",
    descriptionEn: "A stormy expression of wounded trust and deep, unhidden emotion. The extraordinary vocals carry the full weight of the curse, but also the purifying relief that follows it. This work masterfully turns human pain into a strong and liberating sound.",
    descriptionRu: "Бурное выражение раненого доверия и глубокой, нескрываемой эмоции. Необыкновенный вокал несет всю тяжесть проклятия, но и очищающее облегчение, которое следует за ним. Это произведение мастерски превращает человеческую боль в сильный и освобождающий звук."
  },
  {
    titleMk: "Не кажувај либе добра ноќ",
    titleEn: "Don't Say Goodnight, My Love",
    titleRu: "Не говори спокойной ночи, любимая",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Романтична и тајновита ноќна исповед во која вљубените очајно се обидуваат да го сопрат времето. Мелодијата потсетува дека секој заеднички миг е бесценето драгоцен и лесно минлив. Песната вечно живее во тивката молитва оваа ноќ никогаш да не заврши.",
    descriptionEn: "A romantic and secretive night confession where lovers desperately try to stop time. The melody reminds us that every shared moment is infinitely precious and easily fleeting. The song lives eternally in the quiet prayer that this night will never end.",
    descriptionRu: "Романтичная и тайная ночная исповедь, в которой влюбленные отчаянно пытаются остановить время. Мелодия напоминает, что каждое совместно проведенное мгновение бесконечно ценно и легко мимолетно. Песня вечно живет в тихой молитве, чтобы эта ночь никогда не кончалась."
  },
  {
    titleMk: "Отвори ми бело Ленче",
    titleEn: "Open the Door for Me, Fair Lenche",
    titleRu: "Открой мне, белая Ленче",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Староградска приказна за една искрена љубов што трпеливо чека пред затворените порти. Во неа прекрасно се мешаат младешкиот копнеж и срамежливата воздржаност. Песната автентично го чува духот на тивките сокаци и длабоко скриените чувства.",
    descriptionEn: "An urban folk tale about a sincere love patiently waiting before closed gates. Youthful longing and shy restraint beautifully mix within it. The song authentically preserves the spirit of quiet alleys and deeply hidden feelings.",
    descriptionRu: "Городская история об искренней любви, терпеливо ждущей у закрытых ворот. В ней прекрасно смешиваются юношеская тоска и застенчивая сдержанность. Песня достоверно хранит дух тихих переулков и глубоко скрытых чувств."
  },
  {
    titleMk: "Дали чекаш стара мајчице",
    titleEn: "Are You Waiting, Old Mother",
    titleRu: "Ждёшь ли ты, старая матушка",
    artistMk: "Гоце Арнаудов",
    artistEn: "Goce Arnaudov",
    artistRu: "Гоце Арнаудов",
    descriptionMk: "Длабока и болна печалбарска исповед што ја отсликува тежината на далечината од родниот дом. Во неа најискрено се чувствува огромната тишина меѓу синот и неговата мајка. Оваа песна во себе ја носи сета агонија на бескрајното чекање пред портата.",
    descriptionEn: "A deep and painful migrant confession that reflects the burden of distance from the native home. Within it, one most sincerely feels the immense silence between the son and his mother. This song carries within itself all the agony of endless waiting at the gate.",
    descriptionRu: "Глубокая и болезненная исповедь мигранта, отражающая тяжесть расстояния от родного дома. В ней наиболее искренне чувствуется огромная тишина между сыном и его матерью. Эта песня несет в себе всю агонию бесконечного ожидания у ворот."
  },
  {
    titleMk: "Јас сум чисто македонче",
    titleEn: "I Am a Pure Macedonian",
    titleRu: "Я чистый македонец",
    artistMk: "Александар Сариевски",
    artistEn: "Aleksandar Sarievski",
    artistRu: "Александар Сариевски",
    descriptionMk: "Едноставна, но исклучително искрена песна за националната припадност и личниот идентитет. Во неа зрачи една посебна детска чистота, радост и гордост кон сопственото потекло. Песната претставува лесна, но многу силна порака за љубовта кон своите корени.",
    descriptionEn: "A simple but exceptionally sincere song about national belonging and personal identity. It radiates a special childlike purity, joy, and pride towards one's own origins. The song represents a light, yet very strong message about the love for one's roots.",
    descriptionRu: "Простая, но исключительно искренняя песня о национальной принадлежности и личной идентичности. Она излучает особую детскую чистоту, радость и гордость за свое происхождение. Песня представляет собой легкое, но очень сильное послание о любви к своим корням."
  },
  {
    titleMk: "Кирјана вино продава",
    titleEn: "Kirjana is Selling Wine",
    titleRu: "Кирьяна продаёт вино",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Жива и разиграна македонска песна со лесен, заразен ритам и исклучително топла атмосфера. Преку шармот на Кирјана, таа совршено го пренесува духот на старите меани и боемските дружења. Ова дело е вистински извор на радост, хумор и секојдневна ведрина.",
    descriptionEn: "A lively and playful Macedonian song with a light, infectious rhythm and an exceptionally warm atmosphere. Through Kirjana's charm, it perfectly conveys the spirit of old taverns and bohemian gatherings. This work is a true source of joy, humor, and everyday serenity.",
    descriptionRu: "Живая и игривая македонская песня с легким, заразительным ритмом и исключительно теплой атмосферой. Через обаяние Кирьяны она прекрасно передает дух старых таверн и богемных посиделок. Это произведение — настоящий источник радости, юмора и повседневной безмятежности."
  },
  {
    titleMk: "Едно име имаме",
    titleEn: "We Have One Name",
    titleRu: "У нас одно имя",
    artistMk: "Јонче Христовски",
    artistEn: "Jonce Hristovski",
    artistRu: "Джонче Христовский",
    descriptionMk: "Силна, достоинствена и обединувачка песна која буди гордост за заедништвото и припадноста. Силниот баритон пренесува кристално јасна порака полна со љубов, без ниту малку непотребна тежина. Таа прерасна во мирен, но исклучително моќен глас на македонското единство.",
    descriptionEn: "A strong, dignified, and unifying song that awakens pride in togetherness and belonging. The strong baritone conveys a crystal clear message full of love, without any unnecessary heaviness. It has grown into a calm, yet exceptionally powerful voice of Macedonian unity.",
    descriptionRu: "Сильная, достойная и объединяющая песня, пробуждающая гордость за единство и принадлежность. Сильный баритон передает кристально ясное послание, полное любви, без малейшей ненужной тяжести. Она переросла в спокойный, но исключительно мощный голос македонского единства."
  },
  {
    titleMk: "Туѓината пуста да остане",
    titleEn: "Cursed Be the Foreign Land",
    titleRu: "Будь проклята чужбина",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Тивка и болна печалбарска болка преточена во безвременска мелодија полна со искрена тага. Во неа се чувствува студенилото на далечината од домот и неподносливата тежина на чекањето. Песната останува како длабок, вечен копнеж по враќањето на родното огниште.",
    descriptionEn: "A quiet and painful migrant sorrow translated into a timeless melody full of sincere sadness. Within it, one feels the coldness of being far from home and the unbearable weight of waiting. The song remains as a deep, eternal longing to return to the native hearth.",
    descriptionRu: "Тихая и болезненная печаль мигранта, переведенная во вневременную мелодию, полную искренней грусти. В ней чувствуется холод вдали от дома и невыносимая тяжесть ожидания. Песня остается глубокой, вечной тоской по возвращению к родному очагу."
  },
  {
    titleMk: "Слушам кај шумат шумите",
    titleEn: "I Hear the Forests Rustling",
    titleRu: "Слышу, как шумят леса",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Епска и моќна народна песна што гордо го носи гласот на планината и споменот на тешката борба. Во нејзините стихови, самата природа станува нем сведок на македонската историја. Мелодијата звучи исклучително широко и длабоко, будејќи чувство на страхопочит.",
    descriptionEn: "An epic and powerful folk song that proudly carries the voice of the mountain and the memory of the difficult struggle. In its verses, nature itself becomes a silent witness to Macedonian history. The melody sounds exceptionally broad and deep, awakening a sense of awe.",
    descriptionRu: "Эпическая и мощная народная песня, гордо несущая голос горы и память о тяжелой борьбе. В ее стихах сама природа становится безмолвным свидетелем македонской истории. Мелодия звучит исключительно широко и глубоко, пробуждая чувство трепета."
  },
  {
    titleMk: "Калеш Анѓа",
    titleEn: "Kalesh Angja",
    titleRu: "Смуглая Анджа",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Херојска и инспиративна приказна за женското достоинство, непоколебливата чест и цврстата вера. Во неа се чувствува тивка, но челична одлука која не се крши пред ниту една закана. Песната со векови опстојува како недопирлив симбол на вистинската внатрешна слобода.",
    descriptionEn: "A heroic and inspiring story of female dignity, unwavering honor, and firm faith. A quiet but iron-clad resolve that doesn't break under any threat is felt within it. The song has endured for centuries as an untouchable symbol of true inner freedom.",
    descriptionRu: "Героическая и вдохновляющая история о женском достоинстве, непоколебимой чести и твердой вере. В ней чувствуется тихое, но железное решение, которое не ломается ни перед какой угрозой. Песня веками сохраняется как неприкасаемый символ истинной внутренней свободы."
  },
  {
    titleMk: "Ако умрам ил загинам",
    titleEn: "If I Die or Perish",
    titleRu: "Если я умру или погибну",
    artistMk: "Јонче Христовски",
    artistEn: "Jonce Hristovski",
    artistRu: "Джонче Христовский",
    descriptionMk: "Заветна песна исполнета со неверојатна решителност и внатрешен мир пред лицето на судбината. Во нејзините стихови чука храброст и сила за која воопшто не се потребни зборови. Силната мелодија остава моќно чувство на хероизам и достоинствен животен крај.",
    descriptionEn: "A covenant song filled with incredible determination and inner peace in the face of destiny. In its verses beats a courage and strength for which words are completely unnecessary. The strong melody leaves a powerful sense of heroism and a dignified end of life.",
    descriptionRu: "Заветная песня, наполненная невероятной решимостью и внутренним миром перед лицом судьбы. В ее стихах бьется мужество и сила, для которых слова совершенно не нужны. Сильная мелодия оставляет мощное чувство героизма и достойного конца жизни."
  },
  {
    titleMk: "Море сокол пие",
    titleEn: "A Falcon Drinks Water",
    titleRu: "Сокол пьёт воду",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Мистична и архаична народна песна во која самата природа ја презема улогата на гласник наместо човекот. Нејзините фолклорни слики се едноставни, но кријат многу длабока порака. Хипнотичната мелодија носи древно чувство на бескраен простор и апсолутна слобода.",
    descriptionEn: "A mystical and archaic folk song in which nature itself takes the role of a messenger instead of man. Its folklore images are simple, but hide a very deep message. The hypnotic melody carries an ancient feeling of endless space and absolute freedom.",
    descriptionRu: "Мистическая и архаичная народная песня, в которой сама природа берет на себя роль вестника вместо человека. Ее фольклорные образы просты, но скрывают в себе очень глубокое послание. Гипнотическая мелодия несет древнее чувство бесконечного пространства и абсолютной свободы."
  },
  {
    titleMk: "Не си го продавај Кољо чифликот",
    titleEn: "Don't Sell the Farm, Koljo",
    titleRu: "Не продавай ферму, Кольо",
    artistMk: "Народна",
    artistEn: "Traditional",
    artistRu: "Народная",
    descriptionMk: "Трогателна и многу мирна музичка поука за непроценливата вредност на корените и дедовината. Во неа лежи древна мудрост која е родена директно од македонското животно искуство. Песната тивко, но упорно нè потсетува на оние нешта што навистина вредат да се чуваат.",
    descriptionEn: "A touching and very peaceful musical lesson about the priceless value of roots and ancestral land. In it lies an ancient wisdom born directly from the Macedonian life experience. The song quietly but persistently reminds us of those things that are truly worth keeping.",
    descriptionRu: "Трогательный и очень спокойный музыкальный урок о бесценности корней и земли предков. В ней кроется древняя мудрость, рожденная непосредственно из македонского жизненного опыта. Песня тихо, но настойчиво напоминает нам о тех вещах, которые действительно стоит беречь."
  }
];

export const TRANSLATIONS: Record<Language, any> = {
  mk: {
    stationName: "Македонско народно радио",
    slogan: "Кој пее, зло не мисли",
    live: "Во живо",
    offline: "Радиото е во прекин",
    aboutSongLabel: "За македонската народна песна:",
    listenLive: "Слушајте во живо",
    folkMusic: "Македонска народна музика",
    editorsNote: "Белешка од уредникот",
    aboutStation: "За радио станицата",
    missionTitle: "Мисија на радиото",
    missionDescription: "„Македонско народно радио“ е непрофитно интернет радио посветено на зачувување и промоција на изворниот македонски народен мелос.",
    missionFooter: "",
    footerLine1: "Културно наследство во етер",
    footerLine2: "с.Леуново, Маврово, Македонија",
    stop: "Стопирај",
    listen: "Слушај во живо",
    mute: "Исклучи звук",
    unmute: "Вклучи звук",
    defaultInsight: "Гласот на традицијата одекнува низ етерот."
  },
  en: {
    stationName: "Macedonian Traditional & Folk Radio",
    slogan: "He who sings, thinks no evil",
    live: "Live",
    offline: "Radio is offline",
    aboutSongLabel: "About the Macedonian folk song:",
    listenLive: "Listen live",
    folkMusic: "Macedonian folk music",
    editorsNote: "Editor's note",
    aboutStation: "About the radio station",
    missionTitle: "Radio Mission",
    missionDescription: "Macedonian Folk Radio is a non-profit internet radio dedicated to the preservation and promotion of authentic Macedonian folk melodies.",
    missionFooter: "Available 24/7, anywhere in the world, for everyone who carries the Macedonian beat in their heart.",
    footerLine1: "Cultural heritage on air",
    footerLine2: "v.Leunovo, Mavrovo, Macedonia",
    stop: "Stop",
    listen: "Listen live",
    mute: "Mute",
    unmute: "Unmute",
    defaultInsight: "The voice of tradition echoes through the airwaves."
  },
  ru: {
    stationName: "Македонское народное радио",
    slogan: "Кто поёт, тот зла не мыслит",
    live: "В прямом эфире",
    offline: "Радио не в сети",
    aboutSongLabel: "О македонской народной песне:",
    listenLive: "Слушайте в прямом эфире",
    folkMusic: "Македонская народная музыка",
    editorsNote: "Заметка редактора",
    aboutStation: "О радиостанции",
    missionTitle: "Миссия радио",
    missionDescription: "«Македонское народное радио» — это некоммерческое интернет-радио, посвященное сохранению и продвижению аутентичных македонских народных мелодий.",
    missionFooter: "Доступно 24/7 по всему миру для каждого, кто несет в сердце македонский ритм.",
    footerLine1: "Культурное наследие в эфире",
    footerLine2: "с.Леуново, Маврово, Македония",
    stop: "Stop",
    listen: "Слушать онлайн",
    mute: "Выключить звук",
    unmute: "Включить звук",
    defaultInsight: "Голос традиции разносится в эфире."
  }
};

export const COLORS = {
  background: 'bg-[#0f172a]',
  surface: 'bg-[#1e293b]',
  accent: 'text-[#ecfdf5]',
  muted: 'text-[#94a3b8]',
};
